name: Build APK with Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: android debug
        workdir: .
        buildozer_version: stable

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: work-hour-calculator-apk
        path: bin/*.apk
        retention-days: 30
        if-no-files-found: error
